### ISSUE TITLE
hover expanding menus don't open in iOS

### ISSUE THREAD

**Issue by selfsame** [stephomi/yagui#1]
can be fixed by adding an empty `onclick` attribute to their elements, as per https://stackoverflow.com/questions/35187970/css-hover-not-working-on-ios-safari-and-chrome

**Comment by stephomi** [comment]
https://stephaneginier.com/archive/yagui2/
https://stephaneginier.com/archive/yagui3/
https://stephaneginier.com/archive/yagui4/
Are any of these links working for you?

**Comment by selfsame** [comment]
yes 2 and 3 work

**Comment by stephomi** [comment]
Should be fixed
